os: linux

language: ruby

rvm:
  - 2.4.9
  - 2.5.7
  - 2.6.5
  - jruby-9.2.8.0
  - rbx-4.5

jdk:
  - openjdk8

jobs:
  fast_finish: true
  allow_failures:
    - rvm: rbx-4.5

env:
  global:
    - JRUBY_OPTS="--debug"

bundler_args: --without development

cache: bundler

before_install:
  - gem install bundler

script:
  - bundle exec rake
